name: Workflow

on:
  schedule:
    - cron: '30 4 * * 1'
    - cron: '30 4 * * 2'
    - cron: '30 4 * * 3'
    - cron: '30 4 * * 4'

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          GPG_SECRET_PASSPHRASE: ${{ secrets.GPG_SECRET_PASSPHRASE }}
      - name: Monday
        if: github.event.schedule == '30 4 * * 1'
        run: make main 
      - name: Tuesday
        if: github.event.schedule == '30 4 * * 2'
        run: make radio 
      - name: Wednesday
        if: github.event.schedule == '30 4 * * 3'
        run: make this-is 
      - name: Thursday
        if: github.event.schedule == '30 4 * * 4'
        run: make wakeup
      - name: push
        run: make rclone-install && rclone purge s3:bucket && rclone sync output/ s3:bucket/ --ignore-checksum --ignore-size --s3-upload-cutoff 0 --no-gzip-encoding
        env:
          RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${{ secrets.RCLONE_CONFIG_S3_ACCESS_KEY_ID }}
          RCLONE_CONFIG_S3_ACL: ${{ secrets.RCLONE_CONFIG_S3_ACL }}
          RCLONE_CONFIG_S3_ENDPOINT: ${{ secrets.RCLONE_CONFIG_S3_ENDPOINT }}
          RCLONE_CONFIG_S3_PROVIDER: ${{ secrets.RCLONE_CONFIG_S3_PROVIDER }}
          RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${{ secrets.RCLONE_CONFIG_S3_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_S3_TYPE: ${{ secrets.RCLONE_CONFIG_S3_TYPE }}
