name: Workflow

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt large secret
        run: GPG_SECRET_PASSPHRASE=$GPG_SECRET_PASSPHRASE ./decrypt_secret.sh
        env:
          GPG_SECRET_PASSPHRASE: ${{ secrets.GPG_SECRET_PASSPHRASE }}
      - name: makefile
        run: make main 

